# Generated by Django 2.1.5 on 2019-02-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='presentation',
            table='t_presentation',
        ),
    ]
