# Generated by Django 2.1.5 on 2019-02-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190206_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profileUrl',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentation',
            name='createdAt',
            field=models.DateField(default='2019-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentation',
            name='thumbnailUrl',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
